### ISSUE TITLE
Appアイコンに画像をアップロードすると表示が崩れる

### ISSUE THREAD

**Issue by tmonoi** [Newt-Inc/newt-docs-starter-nuxtjs#1]
Appアイコンに画像をアップロードするとテンプレートの表示が崩れてしまいます

![スクリーンショット 2022-02-09 17 13 09](https://user-images.githubusercontent.com/13725292/153153322-eca91e4a-95e2-47d6-9976-26d7789c2452.png)

**Comment by atsushifujikawa** [comment]
対応しました🚀

<img width="1638" alt="スクリーンショット 2022-02-17 17 50 21" src="https://user-images.githubusercontent.com/81555622/154439444-791358ee-0224-4894-bd58-592b53f43aa0.png">
